version: '3.8'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app_network
        command: >
            sh -c "
            mkdir -p /var/www/storage /var/www/bootstrap/cache &&
            chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
            php-fpm
            "

    webserver:
        image: nginx:alpine
        container_name: webserver
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app_network

    db:
        image: postgres:16
        container_name: db
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/postgresql/data
            - ./docker/postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./docker/postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
        command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
        ports:
            - ${POSTGRESS_PORT}:5432
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    dbdata:
        driver: local
